// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Core.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HighestEducation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HighestEducation = 2,
                            Name = "Angel Hernandez",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            HighestEducation = 1,
                            Name = "Ryan Smith",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            HighestEducation = 3,
                            Name = "Courtney Bush",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            HighestEducation = 2,
                            Name = "Lorenzo White",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("MyApp.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HiredCandidateId")
                        .HasColumnType("int");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredEducation")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HiredCandidateId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecruiterId = 2,
                            RequiredEducation = 2,
                            Status = "Opened",
                            Title = "Software Developer II"
                        },
                        new
                        {
                            Id = 2,
                            RecruiterId = 2,
                            RequiredEducation = 3,
                            Status = "Opened",
                            Title = "Senior Software Developer"
                        },
                        new
                        {
                            Id = 3,
                            RecruiterId = 1,
                            RequiredEducation = 1,
                            Status = "Opened",
                            Title = "Software Developer - Entry"
                        },
                        new
                        {
                            Id = 4,
                            RecruiterId = 1,
                            RequiredEducation = 2,
                            Status = "Opened",
                            Title = "Software Developer I"
                        },
                        new
                        {
                            Id = 5,
                            RecruiterId = 2,
                            RequiredEducation = 1,
                            Status = "Opened",
                            Title = "Software Developer - Entry"
                        },
                        new
                        {
                            Id = 6,
                            RecruiterId = 2,
                            RequiredEducation = 2,
                            Status = "Opened",
                            Title = "Software Developer I"
                        });
                });

            modelBuilder.Entity("MyApp.Core.Models.JobCandidateMatch", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId", "CandidateId");

                    b.HasIndex("CandidateId");

                    b.ToTable("JobCandidateMatches");
                });

            modelBuilder.Entity("MyApp.Core.Models.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Recruiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Susan Berkly"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tom Holms"
                        });
                });

            modelBuilder.Entity("MyApp.Core.Models.Job", b =>
                {
                    b.HasOne("MyApp.Core.Models.Candidate", "HiredCandidate")
                        .WithMany()
                        .HasForeignKey("HiredCandidateId");

                    b.HasOne("MyApp.Core.Models.Recruiter", null)
                        .WithMany("Jobs")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HiredCandidate");
                });

            modelBuilder.Entity("MyApp.Core.Models.JobCandidateMatch", b =>
                {
                    b.HasOne("MyApp.Core.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Core.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MyApp.Core.Models.Recruiter", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
